### ISSUE TITLE
Disable swipe on last card

### ISSUE THREAD

**Issue by brascene** [alexbrillant/react-native-deck-swiper#100]
I've looked through props and methods but could't find this one, does it already exists? Or is there some workaround to disable swipe action on the last card?
Thanks!

**Comment by alexbrillant** [comment]
It would be feasible to make it work with the onSwipe callbacks. The onSwipe callbacks give you a cardIndex that you can use. The Swiper also has props to disable swiping for directions(I should add disableSwipe as well) : https://github.com/alexbrillant/react-native-deck-swiper#swipe-animation-props. 

When onSwipe is being called with the last cardIndex, you could change your state variable to set disableSwiper props to true

**Comment by brascene** [comment]
I though about it, but also thought maybe there's something quicker. Thanks however, great lib :)
