### ISSUE TITLE
get vertical or horizontal movement

### ISSUE THREAD

**Issue by jose920405** [alexbrillant/react-native-deck-swiper#106]
It is possible to know the horizontal and vertical movement of the card.
I need it to make animations with interpolate.

**Comment by phil-hodgson-1st** [comment]
You can grab the swiping movement from the `onSwiping` prop, it returns the X and Y change.

So:
```
onSwiping={(x, y) => {
                console.log('-----');
                console.log('x-value', x);
                console.log('y-value', y);
                console.log('-----');
              }}
```

Then either use setState directly on your main component or pass it through to an action to update the reducer.

This gives you the direct number so where you may call `pan.x.interpolate()`, you can now just call `x`

**Comment by alexbrillant** [comment]
exactly @phil-hodgson-1st thanks
