### ISSUE TITLE
React native deck swiper is really slow ?

### ISSUE THREAD

**Issue by sunnynegi** [alexbrillant/react-native-deck-swiper#109]
Hi team, i am using you deck swiper for showing multiple profile, but your deck swiper is really slow, it's take time for rendering. I am using your basic example. Is there any way so i can fast.

**Comment by Hades1996** [comment]
Have you tried disabling dev mode?

**Comment by sunnynegi** [comment]
Yes tried with disabling the dev mode. But same it's slow, 
**# Issue i am facing**
I am facing two issues one is deck swiper stuck half out when i try to move it if i try to swipe it must get back its original position(center) if not completely swiped
and the second issue is it's taking around 1 to 2  seconds to load the next decker.

**Comment by alexbrillant** [comment]
@sunnynegi what react native version are you using ?

**Comment by sunnynegi** [comment]
@alexbrillant  React native version 0.51.0.

**Comment by sunnynegi** [comment]
Any help on this issue, why transition is slow, Or is there any alternative for this.

**Comment by dani-sc** [comment]
Strange, for me it's quite fast when running it in non-dev mode. Everything else in your app is fast? What's your setup - Android or iOS and are you running it on a real device or in the emulator?

**Comment by sunnynegi** [comment]
@dani-sc  I am using real device - android

**Comment by miukki** [comment]
if use onSwipeRight or onSwipeLeft and update states in reducers
e.g 
```
        onSwipeRight={() => {
          updateRemainAmount()
        }}
        onSwipeLeft={() => {
          updateRemainAmount()
        }}

```
work clanky, slow and also with FlipCard 
`with import FlipCard from 'react-native-flip-card'
`
also very slow and buggy

**Comment by ossamaweb** [comment]
@miukki If you're using some redux action within the function it will cause that issue. Instead, you can batch the actions using https://github.com/tshelburne/redux-batched-actions
