### ISSUE TITLE
React native 0.52.1 > overlayLabelStyle > borderRadius not working on iOS

### ISSUE THREAD

**Issue by nppull** [alexbrillant/react-native-deck-swiper#112]
React native 0.52.1 > overlayLabelStyle > borderRadius not working on iOS

overlayLabelStyle={{
                                fontSize: 30,
                                fontWeight: 'bold',
                                **borderRadius: 5,**
                                padding: 10
                            }}

**Comment by alexbrillant** [comment]
if you remove it from the style object, it will fix your problem. I don't know how to do this on rn 0.52.1, but this is not related to this package
