### ISSUE TITLE
Overlay not visible on Android

### ISSUE THREAD

**Issue by dvschnitz** [alexbrillant/react-native-deck-swiper#116]
The overlay works well on iOS, however at android the overlay is rendered behind the card element. What can I do to solve this problem?

The top overlay is styled like this:

`top: {
                        element: <Text style={{
                            color: colorBlue,
                            fontSize: 32,
                            borderWidth: 5,
                            borderColor: colorBlue,
                            padding: 8,
                            borderRadius: 5 }}>SUPER</Text>,
                        title: 'SUPER LIKE',
                        style: {
                            wrapper: {
                                flexDirection: 'column',
                                alignItems: 'center',
                                justifyContent: 'center',
                            }
                        }
                    }`

**Comment by dvschnitz** [comment]
I fixed the problem by adding a View around the component:
`<View style={{ flex: 1, backgroundColor: 'transparent' }}>
  //Card Element here
</View>`

**Comment by deadcoder0904** [comment]
Thanks, @dvschnitz I was wondering why my Cards are not swiping on Android & your fix helped me :)
