### ISSUE TITLE
Prevent rendering all the cards while swiping

### ISSUE THREAD

**Issue by roysG** [alexbrillant/react-native-deck-swiper#119]
I have few components inside the deck card and i also inserted some test line of new Date().getTime As text.

When i play and swiping the card i experience some slowly movement on the device, even i am not on debugging.

When i added the test line of the date, i saw that the date is updated in each movement also for the other cards.
I am sure that this is the things that make the slowly movement.

Can i prevent it from happen and stick the date as is without updating it.

Important to say that the date is not state and just a regular text.

**Comment by filiptdz** [comment]
So, as far as I understand it, the Swiper should only render (call renderCard) the first two cards (If set to showSecondCard, otherwise should only render the first one). Could you send a sample of your code? I do not have my buggy code anymore to see, but I had an experience where updating an item of the cards array produced very strange behaviour. Instead, I found that passing other props to the card component which have no relation with the cards array solved my problem. See if there aren't similar occurrences.

**Comment by roysG** [comment]
Yes, the render is rendering only the two cards, But as i see it, the render card suppose to render just the state and not the static text or image.

I am not home right now, but it easy to test the example i gave.
Just add field text with value {new Date().geTime()} and you will see that the the date is always changing while you play with the card movement on the screen.

How can i add option to disable the changing?

The problem: (For instance):
  <View style={styles.container}>
        <Swiper
            cards={['DO', 'MORE', 'OF', 'WHAT', 'MAKES', 'YOU', 'HAPPY']}
            renderCard={(card) => {
                return (
                    <View style={styles.card}>
                        <Text style={styles.text}>{new Date().getTime()}</Text>
                    </View>
                )
            }}
            onSwiped={(cardIndex) => {console.log(cardIndex)}}
            onSwipedAll={() => {console.log('onSwipedAll')}}
            cardIndex={0}
            backgroundColor={'#4FD0E9'}>
            <Button
                onPress={() => {console.log('oulala')}}
                title="Press me">
                You can press me
            </Button>
        </Swiper>
    </View>

**Comment by filiptdz** [comment]
In this case, every time you render a card, it will create a new Date object. The date isn't saved anywhere, and so every time the component renders, it will run the code again, and create a new object. To have this date turn into a static text, you will have to save it to the state, and then you can update it only when you want.

**Comment by roysG** [comment]
Yes, but this is not my main problem, 
My problem is the slowly in movement when i have few components on the card.
Components like: Galley images, blurView ,Text,Buttons show less and more text and states.

Why i feel slowly in the device even when test it on production mode, it is not feel native.

**Comment by filiptdz** [comment]
I guess the only logical explanation is that something is using too much memory, by rendering, updating state or calling APIs. Maybe you can start by trying to remove one component at a time, to see if there is a single culprit, or logging on the console every process they could be calling. Might also be a bad use of the lifecycle (Eg: Changing data on the render function), or having a infinite loop, where the swiper updates the card component, which updates the swiper, and so on.

**Comment by roysG** [comment]
Yee, i also tried it, but not found something specific, i will do more testing and update.

**Comment by roysG** [comment]
Guys, you are AWSOME, this is was just a fucking console.log in the wrong PLACE, TNX
