### ISSUE TITLE
Rendering the first and the second card differently

### ISSUE THREAD

**Issue by filiptdz** [alexbrillant/react-native-deck-swiper#120]
So, I ran into an issue while having to render the first and second card differently, based on user interaction. After swiping, there would be a small, but non-negligible time frame while the "hidden" version of the card would render before updating to the initial one, in the case of using a state boolean to decide which version of the card to display. Thus, the only other option I see is adding a property in each of the cards array's objects to indicate this.
However, doing so adds an unnecessary amount of data in a large dataset, turns the code more bug-prone, and adds a lot of redux calls and code.
My proposed solution is when calling `renderCard`, add a second argument, `isFirstCard`
(on `Swiper.js`, modify line 629 to `const firstCard = this.props.renderCard(firstCardContent, true)` and line 655 to `const secondCard = renderCard(secondCardContent, false)`)
and the function on the `renderCard` prop will, instead of only passing the `cardData`, will be of type `func(cardData, isFirstCard)`. Therefore, you can receive `isFirstCard` if you want to achieve different renders on the first and second cards.
However, I'm not sure if this would be a use case important enough to add this functionality to the project. Let me know what you think, or if there is a simpler way to do this that I haven't thought of.

**Comment by mightym** [comment]
Looking for something similar. In my case I always need to apply special styling/event listeners on the first card. Thanks for the hint. Will try you approach and change those line in the library
