### ISSUE TITLE
Keep the cardIndex always be zero

### ISSUE THREAD

**Issue by wym7230** [alexbrillant/react-native-deck-swiper#125]
I have an array in my state, let's 10,000 elements in this array. I would like to delete very first element once it swiped to free up some memory. But that causes wrong cardIndex tracking. Is there a way to alway keep cardIndex to zero rather than always increment?

**Comment by dmitrika** [comment]
Seems like we can add optional keyExtractor function to get unique keys for cards data. If this idea is ok, I would like to implement it 🤓

**Comment by alexbrillant** [comment]
yes @dmitrika this makes sense. go for it

**Comment by gulisashvili** [comment]
Hey Guys, I am having this issue again , even after using `keyExtractor` 

Any Ideas ?
