### ISSUE TITLE
Old bug is back in 1.4.9: photo flickering after swiping

### ISSUE THREAD

**Issue by boreys** [alexbrillant/react-native-deck-swiper#130]
Version 1.4.8 fixed the problem of flickering. It was solved in version 1.4.8, this new version 1.4.9 bring back old bug. After swiping a photo, there is a flicker on the next photo.

**Comment by webraptor** [comment]
https://github.com/alexbrillant/react-native-deck-swiper/commit/fb640206dbfcf0f10776b76b571e8ae660a87473#commitcomment-28199779

**Comment by webraptor** [comment]
Fixed by https://github.com/luminos-software/react-native-deck-swiper/commit/fccf2a62bacce2e7328d5065974194ad91ffce53. PR will follow shortly.

**Comment by novakben** [comment]
Was this fixed? I tried ```yarn upgrade react-native-deck-swiper``` but still get this.

**Comment by webraptor** [comment]
Yes, make sure you're on version 1.5.9

**Comment by novakben** [comment]
I am

**Comment by webraptor** [comment]
Does it happen on both platforms or just iOS? Try clearing metro and haste and derived data.
The idea is that since 1.4.8 the rendering of the cards has been changed and second card re-rendered as first one, but animated ...

**Comment by novakben** [comment]
Yep, iOS. I'm using expo, so no access to Xcode available. 
But after upgrading to 1.5.9 I noticed there's an issue with the stack.
if the stack size is > 3 and stackSeperation is > 5, the middle card is missing. This also correlates with the image flicker. Whenever there's a gap in the stack, the photo flickers on transition.

**Comment by webraptor** [comment]
Ah, I see... in that case please open a new bug with repro steps (expo / stacksize, stackseparation) and hopefully some of us will be able to fix it. I'll try to test on our end with different stacksize / stackseparation values see if it happens without expo.
