### ISSUE TITLE
stackSize is not updated when number of cards is updated 

### ISSUE THREAD

**Issue by aminoo540** [alexbrillant/react-native-deck-swiper#139]
it shows an error  undefined "singleValue.stopTracking"

**Comment by webraptor** [comment]
stackSize is used to define the number of cards shown in the deck of cards. It should not update when new cards are pushed into the deck or when cards are changed all together.

**Comment by aminoo540** [comment]
Example : I have 9 cards and the stackSize is 1 .  while swiping I push new cards so let's say the total is 16. in the 9th card it shows an error undefined "singleValue.stopTracking" because  I think the swiper component doesn't update the cards so it will not find the next card .

**Comment by webraptor** [comment]
Try testing with the master branch from the PR over here: #138
Some changes over there ensure that when new cards are introduced the component will re-render, technically fixing your issue.

**Comment by webraptor** [comment]
@alexbrillant I think we can close this one since it was fixed by https://github.com/alexbrillant/react-native-deck-swiper/pull/138
