### ISSUE TITLE
How to swipe to previous card using by a function?

### ISSUE THREAD

**Issue by wym7230** [alexbrillant/react-native-deck-swiper#141]
Is there a way to swipe to previous card by function? e.g. using a button calls swiper reference and move the previous card back on the stack.

**Comment by angryanatole** [comment]
you should try using jumpToCardIndex() method

**Comment by webraptor** [comment]
```
<Swiper
   {...this.yourSwiperProps}
   ref={swiper => { this.swiper = swiper; }}
```
Then in your parent node, or wherever you pass this.swiper reference:
```
this.swiper.swipeBack(() => { /* callback fnc if required */ });
```

For some reason, it looks like the method is missing from the readme section.
