### ISSUE TITLE
Error while updating property 'transform' of a view managed by: RCTView

### ISSUE THREAD

**Issue by sergeylaptev** [alexbrillant/react-native-deck-swiper#145]
Hello. I have the case where I dynamically change length of cards. E.g. while loading I show 1 card with specific id:
```js
cards = [
  { id: 'loading' }
]
```

And inside renderCard function handle displaying this card respectively. But when loading ended I replace existing cards array (with loading) with array of received items. And here is the issue. `this.initializeStack` is called only inside constructor. It creates animated values for every card in the stack. In my case the state will be looking like this:
![image](https://user-images.githubusercontent.com/5740795/38380144-8e605b5a-390b-11e8-8123-bf3db8b71e0f.png)

But after successful loading we get e.g. 8 items, and `this.calculateStackCardZoomStyle` gets indexes for cards which aren't presented in state. E.g. card with index 4:
![image](https://user-images.githubusercontent.com/5740795/38380208-b8b707d2-390b-11e8-8895-734d5759a410.png)

As you can seen both values for transform are `undefined`.  And app crashes of course. Need to handle case where `cards` prop may have different length through component lifecycle.
![image](https://user-images.githubusercontent.com/5740795/38380333-0cec1a36-390c-11e8-8fbc-9863cd91f616.png)

**Comment by webraptor** [comment]
This issue has been addresses in the latest commit within the PR over here: https://github.com/alexbrillant/react-native-deck-swiper/pull/138
