### ISSUE TITLE
Issue with last card after adding new cards to swiper

### ISSUE THREAD

**Issue by angryanatole** [alexbrillant/react-native-deck-swiper#15]
First of all, thank you for the awesome library.

I have the following issue: while swiping cards, when I have few cards left, I make a request to server to add additional data. I use redux, catch new props and make setState(). Therefore, I add new cards to my Swiper.

Let's say I have 9 cards and load additional data when 3 cards are left. Till the 9'th card everything works fine. When I try to swipe the 9'th card, no new cards are rendered behind it - I see a blank view (though I know that new cards are already in the state). Immediately after the swipe of the that card (when swipe event is triggered), it makes new cards visible with no additional actions from me. And everything works fine again.

Thank you for your help.

**Comment by alexbrillant** [comment]
Here is an example with lazy loading :
https://gist.github.com/alexbrillant/156c855d9df8911829529b3014491710

It was working when I wrote it. Did you implemented lazy loading in the same way as this example?

**Comment by angryanatole** [comment]
@alexbrillant well, actually your example works perfectly. It seems that I have some problems with my own code and it is not connected to the library.

Thank you for fast reply and for your work!

**Comment by angryanatole** [comment]
@alexbrillant hello again :)

Just wanted to ask you before opening a new issue in case I am missing something: have you tried to swipe all the cards and after that add new ones to the swiper? In my case component doesn't update and doesn't show new items. With lazy loading everything is fine.
