### ISSUE TITLE
How to swipe to previous card with animation.

### ISSUE THREAD

**Issue by jariwalabhavesh** [alexbrillant/react-native-deck-swiper#164]
I had read documentation and find-out way to get previous card. and it is working fine but it just put card at top of stack without any animation is there a way to get previous card back with animation??

Any help on this??

I had follow this [example](https://snack.expo.io/H1t_QvBJQ)

**Comment by alexbrillant** [comment]
@jariwalabhavesh this is in the list of things I would like to be in the library. In the overview section, there is a list of features to be done. feel free to contribute

**Comment by Palisand** [comment]
@alexbrillant I see `swipeBack` [calls](https://github.com/alexbrillant/react-native-deck-swiper/blob/master/Swiper.js#L354-L362) `Animated.spring`. Can you give us your thoughts on why you think the animation is failing?
