### ISSUE TITLE
interpolateOpacity doesn't work as it should

### ISSUE THREAD

**Issue by webraptor** [alexbrillant/react-native-deck-swiper#17]
The interpolate opacity method doesn't work properly. Tested it thoroughly on an iPhone 6 with a card in portrait mode and only Oy axis gets animated.
IE: swiping card to top and bottom applies opacity interpolation, swiping it left and right doesn't apply any interpolation and the card remains at opacity 1 throughout the swipe movement.

`
interpolateOpacity = () => {
    const animatedValueX = Math.abs(this._animatedValueX);
    const animatedValueY = Math.abs(this._animatedValueY);
    let opacity;

    if (animatedValueX > animatedValueY) {
      opacity = this.state.pan.x.interpolate({
        inputRange: this.props.inputOpacityRangeX,
        outputRange: this.props.outputOpacityRangeX
      });
    } else {
      opacity = this.state.pan.y.interpolate({
        inputRange: this.props.inputOpacityRangeY,
        outputRange: this.props.outputOpacityRangeY
      });
    }

    return opacity;
};
`

**Comment by webraptor** [comment]
It seems the issue is caused by the default inputOpacityRangeX and outputOpacityRangeX . In portrait mode, the default range output for opacity is always 1.

**Comment by webraptor** [comment]
Perhaps the default values could be updated so that the opacity kicks in sooner so that it is clear for everyone (when initially setting up) how the ranges can be modified.

**Comment by alexbrillant** [comment]
I have tried fixing this issue, but I cannot find how to compare two AnimatedInterporlation values together. I have asked the following question on SO : https://stackoverflow.com/questions/44558466/compare-two-animated-interpolations-objects-together-in-react-native 
@webraptor

**Comment by webraptor** [comment]
Aha, this isn't necessarily an issue, it's just that with the current default values of input/output ranges, it may appear that the horizontal opacity is not working at all in portrait mode of the phone.

Just tried it out with outputOpacityRangeX [0.4, 0.8, 1, 0.8, 0.4] and the horizontal opacity animation is very clear now. Perhaps we could update the default values with these ones.

**Comment by alexbrillant** [comment]
fixed in 1.2.0
