### ISSUE TITLE
SwipeBack - First Card

### ISSUE THREAD

**Issue by anantkgoyal** [alexbrillant/react-native-deck-swiper#176]
Currently when the swipeBackOnSwipe is enabled, it goes back fine however is there a way to not go to the last card when we swipe back from the first card? I could not see anything on the documentation.

**Comment by anantkgoyal** [comment]
In order to work this through, I disabled the swipe every time I entered the first card using a set state. This caused the component to re-render every time. There should be a more efficient way of doing this.

**Comment by steoo** [comment]
I second this, in my opinion, if `infinite` is set to `false` the method `swipeBack` on the first index should be a no-op
