### ISSUE TITLE
this.calculateCardIndexes is not a function

### ISSUE THREAD

**Issue by sazo2300** [alexbrillant/react-native-deck-swiper#194]
So, i get an error saying "TypeError: undefined is not a function (evaluating 'this.calculateCardIndexes(props.cardIndex, props.cards)" when my app starts up.

All ive done is yarn add the package, and then imported it in a component, and tried the usage example in the readme. Ive also tried the full example app.js component, and both give me the same error.

Looking in the node module the function is there as it should be.

Please help 😞

**Comment by dan-katz** [comment]
I'm also getting this error. It doesn't happen when using version 1.5.22 so it must be related to the most recent PR

**Comment by alexbrillant** [comment]
@sazo2300 fixed here  https://github.com/alexbrillant/react-native-deck-swiper/commit/f0d47126412ddbb7e90fe5af5f8e38917ac9b520
