### ISSUE TITLE
[Feature request] Add swiper direction?

### ISSUE THREAD

**Issue by giautm** [alexbrillant/react-native-deck-swiper#2]
I want to know direction of swiper to do some thing. Ex: Vote up if direction is the right side, and otherwise. :D

**Comment by alexbrillant** [comment]
@giautm this is a good ideal, I will add the following callbacks:  onSwipeRight, onSwipeLeft, onSwipeUp, onSwipeDown.

**Comment by alexbrillant** [comment]
the callbacks are available in 1.0.7 👍
