### ISSUE TITLE
Position of Swiper

### ISSUE THREAD

**Issue by leon2835** [alexbrillant/react-native-deck-swiper#204]
Hi there, let's say i want to position the swiper at a certain place, below the "Top Text" and above the "End Text" (center of it), how am i suppose to do it? It seems like i'm wrapping those text with a "View", and "Swiper" between the "Text". But the result is not expected and the swiper show in other place instead between them.
<img width="818" alt="screen shot 2018-12-14 at 2 55 12 pm" src="https://user-images.githubusercontent.com/19604759/49988013-4e6ea080-ffb0-11e8-9660-ef5aeabb39c8.png">

**Comment by rajonali** [comment]
Yeah same thing is happening for me.

**Comment by dcangulo** [comment]
Have you found any solution?

**Comment by webraptor** [comment]
The swiper is absolutely positioned, it's intentional. You'll need to build your screens based on that. Please close this issue as it is not a bug.

**Comment by abassey** [comment]
Hi! @leon2835 were you able to figure out a workaround for this? If you were, would you be comfortable sharing it please? I am stuck on how to do it still

**Comment by OziTFA** [comment]
Maybe one way is to give an absolute position to the 'end text' and set it to the bottom.
