### ISSUE TITLE
Allow Overlay for buttons like tinder

### ISSUE THREAD

**Issue by ramanjaneya-karnati** [alexbrillant/react-native-deck-swiper#206]
Hi,

Can we get overlay labels for button actions. Like not only for swiping.

I'm trying to make tinder swipe cards. I have buttons like, dislike, superlike. can we get like overlayt when i click like button.

Thanks in advance

**Comment by webraptor** [comment]
Already requested [here](https://github.com/alexbrillant/react-native-deck-swiper/issues/198). Please close this issue.

**Comment by 1reldi** [comment]
I did a fix for this. You can check it here
[https://github.com/alexbrillant/react-native-deck-swiper/issues/278](url)
