### ISSUE TITLE
Not working on Android real device

### ISSUE THREAD

**Issue by KoheiTigers** [alexbrillant/react-native-deck-swiper#218]
Do you know how to use react-narive-deck-swiper by Expo?

I tried to use it on Android but it doesn't work (Not rendering). 

However, it works on iOS in same code.
```
<Swiper
                    goBackToPreviousCardOnSwipeRight
                    disableRightSwipe={this.state.cardIndex === 0}
                    cards={finalData}
                    onSwipedLeft={ (cardIndex) => this.onSwiped(cardIndex, 'left')}
                    onSwipedRight={ (cardIndex) => this.onSwiped(cardIndex,'right')}
                    showSecondCard={false}
                    cardVerticalMargin={50}
                    renderCard={(card, index) => {
                        return (
                            <ScrollView contentContainerStyle={styles.card}>
                                <Text style={styles.text}>{card}</Text>
                                {
                                    index !== this.props.data.length
                                        ? <Text
                                            style={styles.pageNumber}>{`Page ${index + 1} / ${this.props.data.length}`}</Text>
                                        : null
                                }
                            </ScrollView>
                        )
                    }}
                    onSwipedAll={() => {
                        this.props.navigation.navigate('Rating', {level: this.props.level});                        
                    }}
                    backgroundColor={'transparent'}
                    stackSize={this.props.data.length}>
</Swiper>
```
```

**Comment by baophamtd** [comment]
I've encountered the same :(. Cannot make Android build now

**Comment by JacobJaffe** [comment]
I believe that the `react-native-view-overflow` dependency _does_ break this on android -- consistently getting an error:
```
requireNativeComponent: "RNViewOverflow" was not found in the UIManager
```
I believe this happens because on Expo the linking step can't occur.

This was introduced in #222 -- I didn't have any issues until after that update.

**Comment by NainalChauhan** [comment]
@JacobJaffe could you please tell me that where the `useViewOverflow` prop should be defined?

**Comment by ugene123** [comment]
@JacobJaffe You saved my life, thank you!! Was banging my head against the wall why it didn't work on a real android device and was crashing my app.

**Comment by KoheiTigers** [comment]
@JacobJaffe
Thank you for your advices and I'm sorry for replying so late.
I solved this issue

**Comment by mightym** [comment]
Is react-native-view-overflow somehow involved when the labels on the cards are shown? Because I just realize that there are no labels on the cards on android.

**Comment by JorgeMoralesLopez** [comment]
Hi, I have updated expo sdk 33 to sdk 34 and now this happens to me Unable to resolve "react-native-view-overflow" from "node_modules / react-native-deck-swiper / Swiper.js"
It seems that a dependency on react-native-deck-swiper is missing.
How can I solve this?
"react-native-deck-swiper": "^ 1.5.22",

**Comment by altany** [comment]
@mightym I am having the same issue. Did you ever manage to fix it? I suspect it has to do with styling options
