### ISSUE TITLE
Warning: Can't call `forceUpdate` on a component that is not yet mounted

### ISSUE THREAD

**Issue by MindFreeze** [alexbrillant/react-native-deck-swiper#223]
```
Warning: Can't call `forceUpdate` on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the `Swiper` component., forceUpdate, Swiper
```
This seems to be caused by this line https://github.com/alexbrillant/react-native-deck-swiper/blob/ad9ae4f82eb77674606523204fb3a290e2c224bc/Swiper.js#L112 
You shouldn't call `forceUpdate()` from the constructor.

**Comment by PavelPolyakov** [comment]
hi @alexbrillant,

I've also experienced this warning and I see there are two open PR which, I assume, fix this warning. Do you think it's a bug? Can you, maybe, merge one of them?

Regards,

**Comment by dcangulo** [comment]
Hello @alexbrillant 

We need this. Please merge. Thanks. :)

**Comment by ZiedBeta** [comment]
Hi, 
I have updated the package to 1.6.7, I am still having this warning.

Are there any elements we should be aware of ?

Many thanks

**Comment by srishtichouksey** [comment]
Hi 
I also have same issue when I am calling a func  validatePwd()  inside a constructor,
I resolved this issue by passing a flag as a argument in validatePwd function and then checking if inside validatePwd if flag is true then it will call forceUpdate()  otherwise not.
Thanks
