### ISSUE TITLE
Second Card not flush

### ISSUE THREAD

**Issue by lightninglu10** [alexbrillant/react-native-deck-swiper#227]
Hey guys, the second card in the stack is rendered slightly lower than the first, and then it has an animation to bring it to the front. Is there anyway to make the cards flush?

For example:

<img width="342" alt="screen shot 2019-02-21 at 8 06 21 pm" src="https://user-images.githubusercontent.com/2453737/53219299-4c5e3900-3614-11e9-9347-42de9fda3d38.png">

**Comment by pierregoutheraud** [comment]
Prop stackSeparation={0}

**Comment by lightninglu10** [comment]
Awesome, that works. Not sure how I didn't see that...
