### ISSUE TITLE
getting these errors or exceptions

### ISSUE THREAD

**Issue by ManalLiaquat** [alexbrillant/react-native-deck-swiper#230]
![screenshot_1](https://user-images.githubusercontent.com/36041100/53560416-18cc6300-3b6e-11e9-8c1e-0dbb82dbb901.png)
![screenshot_2](https://user-images.githubusercontent.com/36041100/53560417-18cc6300-3b6e-11e9-997a-0a1234024815.png)

**Comment by webraptor** [comment]
Did you try:
```
remove node_modules && yarn cache clean && yarn
```
?

**Comment by ManalLiaquat** [comment]
> Did you try:
> 
> ```
> remove node_modules && yarn cache clean && yarn
> ```
> ?

Thanks.
