### ISSUE TITLE
The second card is not being animated

### ISSUE THREAD

**Issue by patrickreck** [alexbrillant/react-native-deck-swiper#237]
The second card is not being animated when entering the screen, as you can see on the gif below, it just appears instantly.

Is this intentional?

![Instant](https://user-images.githubusercontent.com/2742100/55023272-ba739280-4ffc-11e9-80dd-5bac81aa78db.gif)

**Comment by webraptor** [comment]
You can see that the second card in your animation zooms in when you swipe the one on top. If you're referring to the process of adding a new card down below the deck, then yes, there's no animation for that.
