### ISSUE TITLE
swipe or show card forcefully

### ISSUE THREAD

**Issue by vishalTechnoFreek** [alexbrillant/react-native-deck-swiper#24]
can I show or swipe any card forcefully from any external functional like below  code
` <ListView
          ref={(comp) => { this._refPreviewListView = comp; return; }}
         />
 this._refPreviewListView.scrollTo({ x: 100 });
`
I want to add all cards at bottom with thumbnail size with change of card bottom cards should move and vice versa and want to apply pagination to it
?????

**Comment by alexbrillant** [comment]
Yes, you can use swiperRef.jumpToCardIndex(cardIndex). Read https://github.com/alexbrillant/react-native-deck-swiper#methods.
