### ISSUE TITLE
Module `react-native-view-overflow` does not exist in the Haste module map

### ISSUE THREAD

**Issue by jonnynfb** [alexbrillant/react-native-deck-swiper#241]
after install the package my app crashes with this message:

`Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native-view-overflow` from `.../node_modules/react-native-deck-swiper/Swiper.js`: Module `react-native-view-overflow` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`. (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.228
    RCTCxxBridge.mm:414
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread
`

I'm on 
```
{
    "react": "16.8.3",
    "react-native": "0.59.1",
}
```

**Comment by mulhaus1** [comment]
I had a similar issue and fixed it by setting the useViewOverflow prop to false

**Comment by NainalChauhan** [comment]
@mulhaus1 where the useViewOverflow prop needs to defined?

**Comment by JacobJaffe** [comment]
I also fixed this with `useViewOverflow` prop -- but in my case (using expo, so no way to have view overflow on android specifically), I only had an issue on android with this. My solution:

```
import { Platform } from 'react-native'

...

<Swiper
  ...props
  useViewOverflow={Platform.OS === 'ios'}
/>
```

**Comment by ruzpuz** [comment]
I get this error even before putting the <Swiper /> component anywhere. Just plain `import Swiper from 'react-native-deck-swiper';` is enough for this error to reproduce.

**Comment by zosmak** [comment]
Yep, everything worked fine only after doing `yarn add react-native-view-overflow`or `npm i react-native-view-overflow -S` and rebuilding the project. For what I saw It's a peerDependency and not a dependency, so it expects that you are using that library on your own project.

**Comment by goranefbl** [comment]
Hey Jacob,

you managed to have it working on expo and android? I am having issue of cards not swiping on android while on ios its working just fine. Can you share your working example?

**Comment by TayfunCesur** [comment]
I fixed this issue by 
`npm install --save react-native-view-overflow`

So funny 😄

**Comment by Nembie** [comment]
> I fixed this issue by
> `npm install --save react-native-view-overflow`
> 
> So funny  Now demo works on IOS simulator

solved by this, thank u!

**Comment by cleberamancio** [comment]
> > I fixed this issue by
> > `npm install --save react-native-view-overflow`
> > So funny  Now demo works on IOS simulator
> 
> solved by this, thank u!
solved my problem, thank u!

**Comment by deadcoder0904** [comment]
@alexbrillant Any ideas why this doesn't work?

**Comment by deadcoder0904** [comment]
Ohh got it after seeing the [source code](https://cdn.jsdelivr.net/npm/react-native-deck-swiper@1.6.7/package.json), `"react-native-view-overflow": "0.0.4",` is only added as a `peerDependency` while it is also a dependency & should be added as a dependency.

**Comment by deadcoder0904** [comment]
I've opened a PR #252 that closes this issue :)

**Comment by tayfunyasar** [comment]
I also have same problem.

> Loading dependency graph, done.
> error: bundling failed: Error: Unable to resolve module `react-native-view-overflow` from `/home/tayfun/dev/gitlab/instaton-mobile/node_modules/react-native-deck-swiper/Swiper.js`: Module `react-native-view-overflow` does not exist in the Haste module map

**Comment by changweining** [comment]
npm install --save react-native-view-overflow
solved by this, thank u

**Comment by ochikov** [comment]
I am using `yarn`. Not fixed with installing the `react-native-view-overflow`. Any ideas ?

**Comment by muhammad-ihsan** [comment]
> I am using `yarn`. Not fixed with installing the `react-native-view-overflow`. Any ideas ?

installing `react-native-view-overflow` with `yarn` will not work, [try this solution](https://github.com/alexbrillant/react-native-deck-swiper/issues/241#issuecomment-527911564)

**Comment by petrovprime** [comment]
If you are **not** using Expo and you want to temporarily fix the problem, then:
`npm install react-native-view-overflow --save`
`react-native link react-native-view-overflow` (do not forget this one)

However if you are using Expo, this won't work as the `react-native-view-overflow` module requires native code (hence react-native link ...). And this is not supported in Expo.

I might be wrong, but `react-native-deck-swiper` depends on an old version of react-native: "^0.49.1" where the overflow functionality wasn't native. That's why it requires the `react-native-view-overflow` module to provide it. 

The right solution would be a patch to this project to stop using `react-native-view-overflow` and switch to the native React Native solution.

If [my PR](https://github.com/alexbrillant/react-native-deck-swiper/pull/269) is accepted, this issue will be fixed.

**Comment by andevelop123** [comment]
> I fixed this issue by
> `npm install --save react-native-view-overflow`
> 
> So funny 😄 Now demo works on IOS simulator

Solved by this, thank you!

**Comment by MikeMajara** [comment]
> I fixed this issue by
> `npm install --save react-native-view-overflow`
> 
> So funny 😄 Now demo works on IOS simulator

Shouldn't this be listed as a dependency somewhere??

**Comment by ptrckdev** [comment]
So this package is not usable with expo?
