### ISSUE TITLE
Stacked cards location

### ISSUE THREAD

**Issue by iceskel** [alexbrillant/react-native-deck-swiper#242]
Hey, is there a way to have the stacked cards (for example when `stackSize` prop is `3`) to show at the top of the stack rather than the bottom? Talking about this bit

<img width="366" alt="Screen Shot 2019-04-18 at 4 25 25 pm" src="https://user-images.githubusercontent.com/7555281/56347332-a20b2800-61f6-11e9-9586-6234749d019e.png">

**Comment by JacobJaffe** [comment]
@iceskel have you tried playing with the `stackSeparation` prop? 
e.g. `StackSeperation={-30}`

**Comment by iceskel** [comment]
I did not, that is exactly what I am after. Thanks!

**Comment by Miko2x** [comment]
@JacobJaffe But how do you get it to be on the right side?

**Comment by AkshayItaliya01** [comment]
> 

Did you find any solution for the right-side stack?
