### ISSUE TITLE
Adjust when the overlay label appears

### ISSUE THREAD

**Issue by rogger-frogger** [alexbrillant/react-native-deck-swiper#267]
Thank you for this library. 
Is it possible to adjust when the overlay label appears? At the moment, it's a bit delayed, user needs to shift the card almost half way through for it to start showing. How can I adjust this so that it starts onDragStart e.g. or as soon as user touches the card? Thanks

**Comment by aupous** [comment]
You can resolve it by add this props to Swiper:
`
inputOverlayLabelsOpacityRangeX={[-width / 3, -1, 0, 1, width / 3]}
            overlayOpacityHorizontalThreshold={1}
`

**Comment by rogger-frogger** [comment]
@aupous thank you very much !

**Comment by aupous** [comment]
@rogger-frogger you are wellcome :D
