### ISSUE TITLE
Swipe Back Card

### ISSUE THREAD

**Issue by HsanBenJobrane** [alexbrillant/react-native-deck-swiper#3]
How can I add a swipe back functionality?

**Comment by alexbrillant** [comment]
It is not implemented yet, but I have thought about it. You can submit a pull request with this feature if you like. Otherwise, I will implement it when I have time.

**Comment by alexbrillant** [comment]
I added a swipeBack method to the component.

SwipeBack configuration props : 
https://github.com/alexbrillant/react-native-deck-swiper#swipe-back-animation-props

swipeBack component method :
https://github.com/alexbrillant/react-native-deck-swiper#methods

I also added a method to jumpTo a card at a givenIndex.

Check out the demo for a working exemple : https://github.com/alexbrillant/react-native-deck-swiper/blob/master/Exemples/App.js

Thanks for your suggestion 👍
