### ISSUE TITLE
ScrollView is not working inside the Swiper.

### ISSUE THREAD

**Issue by kalyanijamunkar10** [alexbrillant/react-native-deck-swiper#302]
@alexbrillant Is there any way to enable scroll inside the card swiper?

**Comment by hbarylskyi** [comment]
@kalyanijamunkar10 I suggest you look into Swiper.js and find the reason for it :)

**Comment by hbarylskyi** [comment]
but why do you have the scroll view inside the card?

**Comment by kalyanijamunkar10** [comment]
It worked when i used <Animated.ScrollView>

**Comment by thame** [comment]
See #165

**Comment by nescroft** [comment]
i think the issue is actually that the renderOverlayLabel has a width and height of 100% and a flex:1 with absolute position so it is covering the scrollview.. the 'like' and 'nope' is covering the scrollview. at least that is part of the issue. in swiper.js

**Comment by AnatuGreen** [comment]
If anyone is still having this issue, here is the latest solution in January 2022:

You have to cover the child or childern of the **View** inside your 'renderCard' with a **'ScrollView'** and a **TouchableOpacity**. See the section of the code below:


....
  renderCard = (cards, index) => {
    return (

      <View style={styles.card}>

      <ScrollView>
      <TouchableOpacity>

       <Text> {cards} </Text>

       </TouchableOpacity>
       </ScrollView>

      </View>
    )
  };
....


Remember to disable vertical scrolling first using verticalSwipe={false} if you wish.

Also, to reduce the opacity change on <TouchOpacity> when you scroll, use the activeOpacity prop to manually edit this, like: : `<TouchableOpacity activeOpacity={.7}>`
