### ISSUE TITLE
Any alternatives to this package now its abandoned?

### ISSUE THREAD

**Issue by siquick** [alexbrillant/react-native-deck-swiper#312]
This is a great package but there have been no commits to master since April 2019, so I guess its finished.

Any alternatives out there that are actively maintained?

**Comment by webraptor** [comment]
I've actually tried to get in touch recently with @alexbrillant to help out with maintaining / taking over but no reply :(

**Comment by jacquesdev** [comment]
@webraptor - i'll see what I can do - it would be amazing if you can take this project over

**Comment by jacquesdev** [comment]
See discussion here: https://github.com/alexbrillant/react-native-deck-swiper/pull/311#issuecomment-662434547

**Comment by jacquesdev** [comment]
It's decided we will fork, see here - https://github.com/alexbrillant/react-native-deck-swiper/issues/324

**Comment by webraptor** [comment]
Just managed to push a new [npm version](https://www.npmjs.com/package/react-native-deck-swiper) out.

**Comment by jacquesdev** [comment]
Good job!
