### ISSUE TITLE
Provide swipeLeft & swipeRight methods?

### ISSUE THREAD

**Issue by lsps9150414** [alexbrillant/react-native-deck-swiper#37]
## Use case

When you want to create a UI like Tinder where there are buttons to trigger actions as alternative to swiping.

**Comment by KhalilKhalaf** [comment]
I implemented this feature by tracking current cardIndex and jumping to the desired cardIndex.

It does not use the animation thought.

**Comment by alexbrillant** [comment]
Added this feature in 1.2.7. 
New methods available : 
swipeLeft, swipeRight, swipeTop, swipeBottom
Checkout the methods section inside the readme
Thanks for sharing this idea
