### ISSUE TITLE
How can I render next card on Right Swipe and previous card on Left Swipe?

### ISSUE THREAD

**Issue by Suyashk44** [alexbrillant/react-native-deck-swiper#42]
Thanks for the great module. I have been trying to render next card on Right Swipe and previous card on Left Swipe, just like simple swiper. Any idea how can I do that?

**Comment by AlmogRnD** [comment]
+1 I would also like to do the same thing is this possible?

**Comment by KhalilKhalaf** [comment]
I am not sure if this is what you are looking for but in the Read Me there is a `swipeBack()`: 

See here ->> https://github.com/alexbrillant/react-native-deck-swiper#methods

**Comment by AlmogRnD** [comment]
@KhalilKhalaf I did this it doesn't work, it seems that `this.swiper.jumpToCardIndex(goBackImage);`

Doesn't work here is my code it's pretty straight forward 

```
_swipeLeft = (cardIndex) => {
        console.log('cardIndex ' + cardIndex)
        const lastImage = cardIndex;
        const goBackImage = cardIndex - 1;
        this.swiper.jumpToCardIndex(goBackImage);
    };
```

Also, cardIndex is not working it always starts with the first item in the array? 

Is this option supported?

**Comment by alexbrillant** [comment]
@AlmogRnD Looks like jumpToCardIndex is broken when called from a onSwipedCallback

**Comment by AlmogRnD** [comment]
Yea, so there is no way to load a specific card

**Comment by AlmogRnD** [comment]
@alexbrillant any plans on fixing this in the next day or two, I have a developer milestone I need to meet and want to know if I should wait or look for another solution/package?

**Comment by Suyashk44** [comment]
I have fixed it. I will make pull request by Monday.

**Comment by AlmogRnD** [comment]
@Suyashk44 Thanks looking forward to it

**Comment by Suyashk44** [comment]
#45 fixed

**Comment by AlmogRnD** [comment]
Thanks did also fix the index issue can't really do anything without?
