### ISSUE TITLE
childrenViewStyle causing Children component position issues

### ISSUE THREAD

**Issue by chrisbull** [alexbrillant/react-native-deck-swiper#47]
I have children components that are on the last screen (once all the cards are gone), but I can't position them correctly, because you are missing the top,left,right, bottom on the childrenViewStyle style. 

Please update with:
```
  childrenViewStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0
  },
```

**Comment by alexbrillant** [comment]
fixed in 1.3.1
