### ISSUE TITLE
[Feature Request] option to set children's position

### ISSUE THREAD

**Issue by lsps9150414** [alexbrillant/react-native-deck-swiper#5]
It would be nice to be able to set the position of `Swiper`'s children. Something like `childrenOnTop`.

**Comment by alexbrillant** [comment]
You can achieve this effect using zIndex on the style props of the children. With the current version, the zIndex has to be greater than 4 to be above all of the cards...

I will add a prop that does this automatically. 
Thanks for making this feature request !

**Comment by alexbrillant** [comment]
I added childrenOnTop prop in v1.1.3 👍

**Comment by lsps9150414** [comment]
Oh thanks for the fast update! But actually I meant on top/bottom of the Y axis not z axis (also nice).

**Comment by alexbrillant** [comment]
I use absolute positioning for the cards, and I don't really know how I could implement it otherwise. Maybe I could add a top margin to make the children below I don'k know. 
@lsps9150414 What do you think ?
