### ISSUE TITLE
Label position messed up and too big

### ISSUE THREAD

**Issue by mxmtsk** [alexbrillant/react-native-deck-swiper#53]
I'd love to have more control over the label. The Font Size is too big for me wich causes the label to have a messed up position too.

Is this possible?

![simulator screen shot 20 08 2017 19 07 21](https://user-images.githubusercontent.com/4848184/29496849-4fba3a94-85db-11e7-9c74-d6673ffc7d8c.png)

**Comment by alexbrillant** [comment]
@mxmtsk Wanna contribute ? You can add a prop called overlayLabelStyles that overrides the default overlay label styles.

**Comment by alexbrillant** [comment]
done in 1.4.0
