### ISSUE TITLE
Next card animation doesn't run when using swipe functions

### ISSUE THREAD

**Issue by AaronBuxbaum** [alexbrillant/react-native-deck-swiper#59]
When swiping, a nice animation runs after the first card has been swiped away, where the second card increases slightly in scale (by default from 0.97 to 1). When using a separate button press to run the swipe function, this animation doesn't occur.

To reproduce:
`<Swiper ref={swiper => { this.swiper = swiper; }} ...`
`<Button onPress={() => this.swiper.swipeLeft()}>`

Observe the missing animation

**Comment by alexbrillant** [comment]
fixed in 1.3.5 ! thanks for pointing that out
