### ISSUE TITLE
Feature Request: Next Card "Hint"

### ISSUE THREAD

**Issue by AaronBuxbaum** [alexbrillant/react-native-deck-swiper#60]
You kind of have this mentioned in your README, but I figure it's worth tracking development.

It would be nice to have the next card peeking out from the bottom of the current card, as a hint for users to visually know that they can swipe.

What needs to be done to make this a reality:
  1. Add marginTop or otherwise shift the second card down X pixels on the Y axis (~10px looks good to me)
  2. Update the "zoom" animation so that it also animates the Y axis back to normal -- in other words, move the card up as well as zoom so that it smoothly transitions
  3. Think about how to display the hint on the second card as an animation is occurring. For example, if you do something similar to the above right now, you'll see a noticeable jump when the new "second card" is rendered. One way is to start rendering the "third" card, if it exists, once swiping begins on the first card, and animate it with opacity, but there are probably better solutions to this problem.

**Comment by saimemre1** [comment]
is it done or not yet ?
