### ISSUE TITLE
Feature Request: onTap

### ISSUE THREAD

**Issue by AaronBuxbaum** [alexbrillant/react-native-deck-swiper#61]
There's a similar request out there for double-tap, but let's separate them out; this one should be easier.

We want a function that's called when a user taps on the card. While this could be implemented at the card level relatively easily, the abstraction level is convenient.

**Comment by althurzard** [comment]
@AaronBuxbaum check #62 please.

**Comment by alexbrillant** [comment]
done in 1.3.6 ! 
check out onTapCard callback : 
https://github.com/alexbrillant/react-native-deck-swiper#event-callbacks
