### ISSUE TITLE
NPM not installling

### ISSUE THREAD

**Issue by intell-gent** [alexbrillant/react-native-deck-swiper#64]
it sits here and does not install ⸨       ░░░░░░░░░░░⸩ ⠦ extract:react-native-deck-swiper: verb lock using /Users

**Comment by intell-gent** [comment]
never mind it just took a while.

**Comment by roots-ai** [comment]
How long?
I am still stuck with this been 15mins.

**Comment by roots-ai** [comment]
Nevermind! Works for me too.

**Comment by vko-online** [comment]
> `https://registry.yarnpkg.com/react-native-deck-swiper/-/react-native-deck-swiper-1.4.6.tgz` is 140mb 
What the heck?
