### ISSUE TITLE
Allow for Styling of Overlay

### ISSUE THREAD

**Issue by dani-sc** [alexbrillant/react-native-deck-swiper#69]
It would be nice if the overlay could be styled as well.

In my case, I would like to apply `elevation` and make the colored area span the entire card.
However, that's not possible at the moment. As I've seen it, even things like margin values are hardcoded in the function `Swiper.js/calculateOverlayLabelWrapperStyle`.

Maybe a similar approach like the prop [cardStyle ](https://github.com/alexbrillant/react-native-deck-swiper#style-props)could be implemented?

**Comment by alexbrillant** [comment]
done in 1.4.0 👍
