### ISSUE TITLE
Rerendering card resets Swiper to first card

### ISSUE THREAD

**Issue by miclaus** [alexbrillant/react-native-deck-swiper#74]
how can i rerender a card, but not reset the Swiper to the first card ?

consider the following within the render function:
```es6
const cardData = this.state.cardData
const myCards = map(cardData, (card, cardIndex) => {
  return (
    <CardComponent
      key={cardIndex}
      prop={card.prop}
      onEvent={this.onEvent}
    />
  )
})

return (
  <Swiper
    ref={swiper => this.swiper = swiper}
    cards={myCards}
    cardVerticalMargin={0}
    cardHorizontalMargin={0}
    infinite={true}
    renderCard={card => card}
    backgroundColor={'transparent'}
    verticalSwipe={false}
    onSwiped={() => false}
    onSwipedAll={() => false}
    onSwipedLeft={() => false}
    onSwipedRight={() => false}
  ></Swiper>
)
```

**Comment by webraptor** [comment]
Also set cardIndex on the Swiper from state. That way when you modify anything on the state, the deck will stay the same.

**Comment by bispul** [comment]
i have cardIndex on the Swiper from state but its still not working. The first card renders again immediately after you swipe that card. Can anyone help please?

**Comment by webraptor** [comment]
Ah, ok .. The bug is re-rendering and swiping will keep the second card to the second one in the original card deck ... We've experienced this issue for about a month now, just created the PR with the fix. https://github.com/alexbrillant/react-native-deck-swiper/pull/76/files

**Comment by alexbrillant** [comment]
@webraptor thanks nice work

**Comment by bispul** [comment]
Don't know why but i am still getting the issue. :(

**Comment by yonahforst** [comment]
@bispul I fixed my issue by adding `cardIndex` to the state and then incrementing it in the `onSwiped` callback

**Comment by bispul** [comment]
@yonahforst i tried that too but still I am getting that issue.
