### ISSUE TITLE
JumpToCardIndex from onTapCard

### ISSUE THREAD

**Issue by jalieven** [alexbrillant/react-native-deck-swiper#75]
I am trying to jump to the next card when a card is tapped but am getting all kinds of strange.
When I do the following (only call jumpToCardIndex) then I get correct behaviour (although the cards don't cycle since I have defined infinite={true} and my cardIndex state variable doesn't get updated, basically I cannot tap beyond the last card).

```Javascript
onTapCard={(cardIndex) => {
   this.swiper.jumpToCardIndex(cardIndex + 1);
}}
```

But when I update my cardIndex state I can tap beyond the last card but then nothing gets rendered.

```Javascript
onTapCard={(cardIndex) => {
   this.setState({
      cardIndex: cardIndex + 1,
   }, () => {
      this.swiper.jumpToCardIndex(cardIndex + 1);
   });
}}
```
Mind you that I am feeding my cardIndex state variable into the Swiper component via the props.

**Comment by alexbrillant** [comment]
The card index props refers to the **cardIndex to start with**. You shouldn't change the cardIndex props being passed to the Swiper. 

However, the ideal of having the cardIndex in the state is a great idea. For now, you should still use a variable for the cardIndex, but don't pass it as a prop. 

I could add a method called advanceCardIndex(step) for this. What do you think ?
