### ISSUE TITLE
Development guide

### ISSUE THREAD

**Issue by pavloko** [alexbrillant/react-native-deck-swiper#86]
Hi all, 

I was wondering how would you go about running development mode for this package?

The way I see it, you should:
1. `cd Exemples && react-native run-ios`
2. make changes to Swiper.js file and see changes in the emulator

But currently, in package.json the path for react-native-deck-swiper is pointing to npm registry, so live changes won't be available.

How do you go about this? Thank you.

**Comment by danbenn** [comment]
I just literally copy pasted Swiper.js and added it as a component, this might be your best solution for any custom work you want to do on the component.

**Comment by alexbrillant** [comment]
@danbenn exactly what I am doing
