### ISSUE TITLE
Tap on card interpreted as swipeLeft

### ISSUE THREAD

**Issue by danbenn** [alexbrillant/react-native-deck-swiper#87]
At least for me, a single tap on a card is interpreted as a swipe.

I've tried setting the horizontalThreshold, verticalThreshold, and onTapCardDeadZone to large values, but it doesn't seem to make a difference.

What I'm trying to do: allow user to tap on card for more detail.

I noticed the onTapCard callback, but it never gets called, only onSwipeLeft.

Any ideas for what might be going wrong?

**Comment by pavloko** [comment]
I'd check [Line237](https://github.com/alexbrillant/react-native-deck-swiper/blob/master/Swiper.js#L237). It seems like `isSwiping` and `this.validPanResponderRelease` both return `true`, which should not be the case with touch. 

Basically, there should simple logic that checks whether this was a tap or movement, and flips the card only if it was a movement.

**Comment by danbenn** [comment]
I copy pasted the example code, and didn't notice that the `onTapCard` callback to `Swiper` was filled with `this.swiper.swipeLeft().` Sorry!

**Comment by bogannathan** [comment]
Just came here for the same reason. Didn't see the onTapCard from the example I copied. oops!
