### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by bispul** [alexbrillant/react-native-deck-swiper#89]
Does this swiper have infinite scroll feature? 
I have a lot of image to show in the swiper so fetching all the data at once might cause performance issues. So, does anyone know how to do it?

**Comment by alexbrillant** [comment]
yes, you can achieve lazy loading. check out the comments in this issue https://github.com/alexbrillant/react-native-deck-swiper/issues/7 

it is not perfect yet, but I am working on it. let me know if you have any ideals
