### ISSUE TITLE
Vertical scrolling inside a card not possible as card starts to swipe

### ISSUE THREAD

**Issue by VlooMan** [alexbrillant/react-native-deck-swiper#91]
If we use a list of items which is longer than the height of card, when we want to scroll the contents so we can get to the bottom of our list then the scroll does not work as the swipe action starts. Any idea how we could possibly resolve that?

**Comment by alexbrillant** [comment]
@VlooMan  
Have you tried to changing the zIndex ? https://facebook.github.io/react-native/docs/layout-props.html#zIndex

There is also the possibility to disable vertical swipe by setting verticalSwipe to false. 
Can you please provide a code sample so I can help you find a solution ?

**Comment by webraptor** [comment]
I think the merge should be reversed until introduced bug is fixed.
On Androids, the entire view is transformed and skewed when panning the card. See screenshot.
Please note that this didn't happen on 1.4.4, only on 1.4.5 (tested on a couple simulators and devices).

![25395166_141846336536044_1647438177_n](https://user-images.githubusercontent.com/864054/33996060-a9c97726-e0e8-11e7-9ed4-2358abf71d52.png)

**Comment by IsaacWIvins** [comment]
Having an issue with this even after the merged pull request. I'm still somewhat new to React-Native so I'm assuming it a "it's me, not you" kind of thing.

I tried setting the zIndex with no luck. I also tried to disable the PanResponder temporarily while the y position was changing in hopes of capturing the position to offset another animated view. No Bueno. I even tried tweaking the input values for animatedValueX but couldn't figure it out.

**Comment by qburnsFB** [comment]
For anyone else running into this issue, I was able to implement this hack below and it worked pretty much perfectly.

https://github.com/facebook/react-native/issues/11206#issuecomment-333617880

**Comment by AnatuGreen** [comment]
If anyone is still having this issue, here is the latest solution in January 2022:

You have to cover the child or childern of the **View** inside your 'renderCard' with a **'ScrollView'** and a **TouchableOpacity**. See the section of the code below:


....
  renderCard = (cards, index) => {
    return (

      <View style={styles.card}>

      <ScrollView>
      <TouchableOpacity>

       <Text> {cards} </Text>

       </TouchableOpacity>
       </ScrollView>

      </View>
    )
  };
....


Remember to disable vertical scrolling first using verticalSwipe={false} if you wish.

Also, to reduce the opacity change on <TouchOpacity> when you scroll, use the activeOpacity prop to manually edit this, like: : `<TouchableOpacity activeOpacity={.7}>`

**Comment by AnatuGreen** [comment]
> If anyone is still having this issue, here is the latest solution in January 2022:
> 
> You have to cover the child or children of the **View** inside your 'renderCard' with a **'ScrollView'** and a **TouchableOpacity**. See the section of the code below:
> 
> .... renderCard = (cards, index) => { return (
> 
> ```
>   <View style={styles.card}>
> 
>   <ScrollView>
>   <TouchableOpacity>
> 
>    <Text> {cards} </Text>
> 
>    </TouchableOpacity>
>    </ScrollView>
> 
>   </View>
> )
> ```
> 
> }; ....
> 
> Remember to disable vertical scrolling first using verticalSwipe={false} if you wish.
> 
> Also, to reduce the opacity change on when you scroll, use the activeOpacity prop to manually edit this, like: : `<TouchableOpacity activeOpacity={.7}>`

Update: TouchableWithoutFeedback seems better for this.
